spring.application.name=school-lost-item-finder

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/todos
spring.datasource.username=root
spring.datasource.password=steve4804.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true